# Generated by Django 3.1.1 on 2020-10-24 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Contact Us Response', 'verbose_name_plural': 'Contact Us Responses'},
        ),
    ]
