# Generated by Django 3.1.1 on 2020-11-07 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance_requests', '0002_auto_20200930_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancerequest',
            name='resolution_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='service_provider_invoice',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
