# Generated by Django 3.1.1 on 2020-09-25 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_listing_show_available_date'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='address_city',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='address_state',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='address_street',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='address_zip',
        ),
        migrations.AddField(
            model_name='customuser',
            name='monthly_rent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='customuser',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='listings.listing'),
        ),
    ]
