# Generated by Django 3.1.1 on 2020-09-26 00:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200925_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='lease_begin',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='customuser',
            name='lease_end',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
