# Generated by Django 3.1.1 on 2020-10-21 02:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0007_auto_20201020_2130'),
        ('users', '0004_auto_20201004_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='lease',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='leases.lease'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='rent_amount',
            field=models.IntegerField(default=0),
        ),
    ]
