# Generated by Django 3.1.1 on 2020-10-22 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20201020_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='rent_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
