# Generated by Django 3.1.1 on 2020-09-23 18:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('monthly_rent', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Monthly Rent')),
                ('security_deposit', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Security Deposit')),
                ('street_address', models.CharField(max_length=200, verbose_name='Street Address')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('state', models.CharField(max_length=100, verbose_name='State')),
                ('zipcode', models.CharField(max_length=20, verbose_name='ZIP Code')),
                ('latitude', models.FloatField(blank=True)),
                ('longitude', models.FloatField(blank=True)),
                ('bedrooms', models.IntegerField(default=0)),
                ('bathrooms', models.FloatField(default=0)),
                ('has_garage', models.BooleanField(default=False)),
                ('square_feet', models.IntegerField(default=0)),
                ('cats_allowed', models.BooleanField(default=False, verbose_name='Are cats allowed?')),
                ('dogs_allowed', models.BooleanField(default=False, verbose_name='Are dogs allowed?')),
                ('is_published', models.BooleanField(default=False, help_text='If not checked, this property will not appear on the site.', verbose_name='Is published?')),
                ('availability', models.CharField(choices=[('available', 'Available'), ('rented', 'Rented')], default='available', max_length=30)),
                ('available_date', models.DateTimeField(blank=True, default=datetime.datetime.now, help_text='Indicates when this property will become available to rent.', verbose_name='Date of availability')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('main_image', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('gallery_image_1', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('gallery_image_2', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('gallery_image_3', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('gallery_image_4', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('gallery_image_5', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('gallery_image_6', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
            ],
        ),
    ]
