# Generated by Django 3.1.1 on 2020-09-24 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_auto_20200923_1951'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listinggalleryimages',
            options={'verbose_name': 'Gallery Image', 'verbose_name_plural': 'Gallery Images'},
        ),
    ]
