# Generated by Django 3.1.1 on 2020-09-24 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_auto_20200924_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='show_available_date',
            field=models.BooleanField(default=False, verbose_name='Show availability date on website?'),
        ),
    ]
