# Generated by Django 3.1.1 on 2020-10-02 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_listing_show_available_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='main_image',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/'),
        ),
    ]
