# Generated by Django 3.1.1 on 2020-10-06 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_auto_20201001_2235'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='school_district',
            field=models.CharField(choices=[('oxford_schools', 'Oxford Schools'), ('lafayette_county_schools', 'Lafayette County Schools')], default='oxford_schools', max_length=50),
        ),
        migrations.AlterField(
            model_name='listing',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
