# Generated by Django 3.1.1 on 2020-10-07 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_auto_20201005_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='has_fence',
            field=models.BooleanField(default=False, verbose_name='Has fenced yard?'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='has_garage',
            field=models.BooleanField(default=False, verbose_name='Has garage?'),
        ),
    ]
