# Generated by Django 3.1.1 on 2020-10-21 02:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField(default=django.utils.timezone.now)),
                ('amount', models.IntegerField(default=0)),
                ('balance', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('due', 'Due'), ('paid', 'Paid'), ('late', 'Late')], default='due', max_length=25)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('parent_charge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transactions.charge')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lease Charge',
                'verbose_name_plural': 'Lease Charges',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('amount', models.IntegerField(default=0)),
                ('balance', models.IntegerField(default=0)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('charges', models.ManyToManyField(related_name='lease_payments', to='transactions.Charge')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lease Payment',
                'verbose_name_plural': 'Lease Payments',
            },
        ),
    ]
