# Generated by Django 3.1.1 on 2020-10-28 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_auto_20201021_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='stripe_payment_id',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
