# Generated by Django 3.1.1 on 2020-11-03 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_auto_20201102_2119'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(fields=('stripe_payment_id',), name='unique_stripe_id'),
        ),
    ]
