# Generated by Django 3.1.1 on 2020-11-03 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_auto_20201102_2136'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['confirmation'], name='confirmation_indx'),
        ),
    ]
