# Generated by Django 3.1.1 on 2020-11-30 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0007_auto_20201103_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='type',
            field=models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], default='online', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='charges',
            field=models.ManyToManyField(blank=True, related_name='lease_payments', to='transactions.Charge'),
        ),
    ]
