# Generated by Django 3.1.1 on 2020-11-30 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0008_auto_20201129_1912'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='payment',
            name='unique_stripe_id',
        ),
        migrations.AlterField(
            model_name='payment',
            name='stripe_payment_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
