# Generated by Django 3.1.1 on 2020-11-30 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0009_auto_20201129_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='confirmation',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
