# Generated by Django 3.1.1 on 2020-10-19 01:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leases', '0003_auto_20201014_2110'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaseCharge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField(default=django.utils.timezone.now)),
                ('amount', models.IntegerField(default=0)),
                ('balance', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('due', 'Due'), ('pending', 'Pending')], default='pending', max_length=25)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('parent_charge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='leases.leasecharge')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lease Charge',
                'verbose_name_plural': 'Lease Charges',
            },
        ),
    ]
