# Generated by Django 3.1.1 on 2020-10-21 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0004_leasecharge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lease',
            name='tenant',
        ),
        migrations.AddField(
            model_name='leasedocument',
            name='description',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
