# Generated by Django 3.1.1 on 2020-10-21 01:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leases', '0005_auto_20201020_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leasecharge',
            name='status',
            field=models.CharField(choices=[('due', 'Due'), ('paid', 'Paid'), ('late', 'Late')], default='due', max_length=25),
        ),
        migrations.CreateModel(
            name='LeasePayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('amount', models.IntegerField(default=0)),
                ('balance', models.IntegerField(default=0)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('charges', models.ManyToManyField(related_name='lease_payments', to='leases.LeaseCharge')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lease Payment',
                'verbose_name_plural': 'Lease Payments',
            },
        ),
    ]
