# Generated by Django 3.1.1 on 2020-10-21 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0006_auto_20201020_2028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leasepayment',
            name='charges',
        ),
        migrations.RemoveField(
            model_name='leasepayment',
            name='tenant',
        ),
        migrations.DeleteModel(
            name='LeaseCharge',
        ),
        migrations.DeleteModel(
            name='LeasePayment',
        ),
    ]
