# Generated by Django 3.1.1 on 2020-10-28 15:59

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0009_stripekey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stripekey',
            name='stripe_publishable_key',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=200)),
        ),
        migrations.AlterField(
            model_name='stripekey',
            name='stripe_secret_key',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=200)),
        ),
    ]
